### ISSUE TITLE
python.exe: No module named convert360

### ISSUE THREAD

**Issue by Boscop** [sunset1995/py360convert#12]
Thanks for this great tool :)
Unfortunately I cannot execute it, any idea what I'm doing wrong?
I tried both python 2.7 and python3, both fail:
```
> python -m convert360 --convert e2c --i equirectangular-0.jpg -o e2c.png --w 512
D:\Program Files\Python27\python.exe: No module named convert360

> python -m py360convert --convert e2c --i equirectangular-0.jpg -o e2c.png --w 512
Traceback (most recent call last):
  File "D:\Program Files\Python27\lib\runpy.py", line 151, in _run_module_as_mai
n
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "D:\Program Files\Python27\lib\runpy.py", line 109, in _get_module_detail
s
    return _get_module_details(pkg_main_name)
  File "D:\Program Files\Python27\lib\runpy.py", line 101, in _get_module_detail
s
    loader = get_loader(mod_name)
  File "D:\Program Files\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "D:\Program Files\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "D:\Program Files\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "D:\Program Files\Python27\lib\site-packages\py360convert\__init__.py", l
ine 1, in <module>
    from .e2c import e2c
  File "D:\Program Files\Python27\lib\site-packages\py360convert\e2c.py", line 3
, in <module>
    from . import utils
  File "D:\Program Files\Python27\lib\site-packages\py360convert\utils.py", line
 68
    out = np.ones((*out_hw, 3), np.float32)
                   ^
SyntaxError: invalid syntax

> python3 -m py360convert --convert e2c --i equirectangular-0.jpg -o e2c.png --w 512
C:\Users\me\scoop\apps\python\current\python.exe: No module named py360convert

> python3 -m py360convert --convert e2c --i equirectangular-0.jpg -o e2c.png --w 512
C:\Users\me\scoop\apps\python\current\python.exe: No module named py360convert._
_main__; 'py360convert' is a package and cannot be directly executed

> python3 -m convert360 --convert e2c --i equirectangular-0.jpg -o e2c.png --w 512
C:\Users\me\scoop\apps\python\current\python.exe: No module named convert360
```

Btw, with this tool, how can I generate 6 different image files for the cubemap faces?

**Comment by BrianPugh** [comment]
I know this issue is quite old, but you are missing a `--w` in your CLI invocation
