### ISSUE TITLE
error in py360convert/utils.py line no: 217

### ISSUE THREAD

**Issue by Anthiel** [sunset1995/py360convert#8]
Hey,
Using your example code : 

```

import numpy as np
from PIL import Image
import py360convert

cube_dice = np.array(Image.open('MyImage.jpg'))

cube_h = py360convert.cube_dice2h(cube_dice)  # the inverse is cube_h2dice
cube_dict = py360convert.cube_h2dict(cube_h)  # the inverse is cube_dict2h
cube_list = py360convert.cube_h2list(cube_h)  # the inverse is cube_list2h
print('cube_dice.shape:', cube_dice.shape)
print('cube_h.shape:', cube_h.shape)
print('cube_dict.keys():', cube_dict.keys())
print('cube_dict["F"].shape:', cube_dict["F"].shape)
print('len(cube_list):', len(cube_list))
print('cube_list[0].shape:', cube_list[0].shape)

```

I've got this error message : 

```
Traceback (most recent call last):
  File "PhotoToCubeMap.py", line 8, in <module>
    cube_h = py360convert.cube_dice2h(cube_dice)  # the inverse is cube_h2dice
  File "C:\Program Files\Python37\lib\site-packages\py360convert\utils.py", line 217, in cube_dice2h
    assert cube_dice.shape[0] == w * 3 and cube_dice.shape[1] == w * 4
AssertionError

```

**Comment by jdiazram** [comment]
Hi. I have the same problem. Could you solve this problem? Thx

**Comment by BrianPugh** [comment]
yes, this library requires certain images to have dimensions with multiples of 3 or 4. The newer exceptions have more informative error messages now.
